### ISSUE TITLE
The term 'otx' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#103]
Hey Guys, 

We started receiving this error out of the blue during ALOpsDockerStart tasks
"The term 'otx' is not recognized as the name of a cmdlet..."

My task  code looks like this:
```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: ${{ parameters.imageName }}
    docker_pull: true
    enable_symbol_loading: true
    accept_image_outdated: true 
```
Full log looks like this:

```
##[debug]INPUT_ENCRYPTION_KEY (empty)
##[debug]INPUT_SQL_SERVER (empty)
##[debug]INPUT_SQL_SERVER_INSTANCE (empty)
##[debug]INPUT_SQL_DATABASE (empty)
##[debug]INPUT_SQL_DATABASE_USER (empty)
##[debug]INPUT_SQL_DATABASE_USER_PASSWORD (empty)
##[debug]INPUT_SQL_BACKUP_FILE (empty)
*** Importing required PS-Functions
##[debug]Leaving C:\agent\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1169\31c96471-0394-4586-82a3-8de9fcc8511e.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invoke-Expression : The term 'otx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]At C:\agent\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1169\ps_modules\Docker\7f14f470-d0de-46c1-8a34-53fd99757bd8.ps1:1 char:1
##[debug]+ Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([S ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : ObjectNotFound: (otx:String) [Invoke-Expression], CommandNotFoundException
##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1169\ps_modules\Docker\7f14f470-d0de-46c1-8a34-53fd99757bd8.ps1: line 1
##[debug]at <ScriptBlock>, <No file>: line 66
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1169\31c96471-0394-4586-82a3-8de9fcc8511e.ps1: line 2
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.CommandNotFoundException: The term 'otx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]The term 'otx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]Processed: ##vso[task.logissue type=error]The term 'otx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]Processed: ##vso[task.complete result=Failed]
Finishing: ALOpsDockerStart
```

**Comment by waldo1001** [comment]
That happens when you enable debug - that doesn't work.

Why did you enable it?

**Comment by gintuoklis** [comment]
You were right, 
One of our developers clicked this option while running the pipeline. 
Let's close the case then.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16342128/78375902-ca3d9380-75cd-11ea-97a9-dc0a1807c91e.png)
