### ISSUE TITLE
Problem with license expiration warning in "ALOps Run TestSuite"

### ISSUE THREAD

**Issue by SimonOfHH** [HodorNV/ALOps#412]
**Describe the bug**
The pipeline normally runs fine. But at the moment we are receiving errors during "Run TestSuite", and I suspect the problem to be the message "Caution: Your program license expires in 10 days."

**the used yaml**
Sorry, but the YAML is so much nested, that it's not so easy to include it 🙄 But since we are using the same templates all over at COSMO CONSULT I don't suspect the templates to be the issue (and I'm also not comfortable adding the complete YAML here)

**the output**
Here is the pipeline-step output:
```
Starting: ALOps Run TestSuite
==============================================================================
Task         : ALOps App Test
Description  : Run AL-TestSuite for Business Central
Version      : 1.444.2571
Author       : Hodor
Help         : Run Business Central Test-Suite and collect results.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                           value
----                           -----
usedocker                       True
fixed_tag                           
nav_serverinstance             BC140
tenant                       default
companyname                         
profile                             
bc_username                         
bc_password                         
bc_authentication    NavUserPassword
bc_webclient_url                    
testfilter                          
disabledtests                       
show_available_tests           False
import_testtoolkit             False
import_action              Overwrite
testpage                      130455
testsuite                    DEFAULT
extensionid                         
installaltesttool              False
failed_test_action           Warning
override_finsql_path                
resultfilename       TestResults.xml



*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: Cosmo Consult SSC GmbH

*** Importing required PS-Functions
*** Working folder: C:\azp\agent\_work\1\s\XXX
***
*** Prepare Docker Session
*** Connect Docker Session
*** Initiate Docker Session
*** Direct PSSession to other container [67d90f5c3775057709fdaa63c4bb7412c32fd1ff67465549aac2af90f5c81f83]
*** Container resolved to hostname [67d90f5c3775]
*** Set Docker Container ErrorActionPreference = Stop
*** Copy Modules to Docker
*** Setup Docker Session
*** Checking for container-specific Test Assemblies
*** Using container-specific Test Assemblies
*** Import Modules in Docker Session
*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
VERBOSE: Loading module from path 'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.
*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\170\Service\Newtonsoft.Json.dll]
*** Import Modules in Docker Session: class_ClientContext
*** Test Context Url: https://67d90f5c3775/BC/cs?tenant=default
*** Setup BC Credentials in Docker
*** Resolve Docker Credentials
*** Set TCP Keep-Alive
*** Start TestSuite
*** Running TestSuite with authentication [NavUserPassword] with User [admin]
*** Run warm-up with page [130455]
*** Warm-up Client Context
WARNING DIALOG: Caution: Your program license expires in 10 days.
CommunicationError : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at <ScriptBlock>, <No file>: line 91
at AwaitState, <No file>: line 236
at InvokeInteraction, <No file>: line 243
at InvokeInteractionAndCatchForm, <No file>: line 261
at OpenForm, <No file>: line 301
at Test-OpenForm, <No file>: line 7
at <ScriptBlock>, <No file>: line 14
at <ScriptBlock>, <No file>: line 1
Current Interaction: Microsoft.Dynamics.Framework.UI.Client.Interactions.CloseFormInteraction
Time spend: 22 seconds
*** Create Client Context
*** Run Available Tests for suite [DEFAULT] with page [130455]
*** Connect TestClient with page [130455]
Show dialog 00000000-0000-0000-0300-0000836bd2d2
Title: Dialog 
WARNING DIALOG: Caution: Your program license expires in 10 days.
CommunicationError : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at <ScriptBlock>, <No file>: line 91
at AwaitState, <No file>: line 236
at InvokeInteraction, <No file>: line 243
at InvokeInteractionAndCatchForm, <No file>: line 261
at OpenForm, <No file>: line 301
at Run-Tests, <No file>: line 46
at <ScriptBlock>, <No file>: line 82
at <ScriptBlock>, <No file>: line 1
Current Interaction: Microsoft.Dynamics.Framework.UI.Client.Interactions.CloseFormInteraction
Time spend: 1 seconds
CommunicationError InnerException : Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass15_0.<EndInvokeInteractions>b__0() in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 307
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action) in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 182
Title: Dialog 
Title: 00000000-0000-0000-0300-0000836bd2d2
[
    {
        "type":  "ClientGroupControl",
        "mappingHint":  "GROUP",
        "name":  "contentGroupControl",
        "children":  [
                         {
                             "type":  "ClientGroupControl",
                             "mappingHint":  "LAYOUTGROUP",
                             "name":  "",
                             "children":  [
                                              {
                                                  "identifier":  "",
                                                  "name":  "Info",
                                                  "type":  "ClientImageControl"
                                              },
                                              {
                                                  "type":  "ClientStaticStringControl",
                                                  "name":  "",
                                                  "value":  "Caution: Your program license expires in 10 days.",
                                                  "identifier":  ""
                                              }
                                          ],
                             "caption":  "",
                             "identifier":  "{B178ABC5-D511-462e-B8D1-D08C35BC1113}"
                         }
                     ],
        "caption":  "",
        "identifier":  "{2DD9E973-CD11-40a0-B5CF-6414BD1D3550}"
    },
    {
        "type":  "ClientGroupControl",
        "mappingHint":  "ACTIONBAR",
        "name":  "",
        "children":  [
                         {
                             "caption":  "OK",
                             "type":  "ClientActionControl",
                             "name":  "{B594146A-9CEF-4767-AE76-E9721CD6FB50}",
                             "identifier":  "{B594146A-9CEF-4767-AE76-E9721CD6FB50}"
                         }
                     ],
        "caption":  "",
        "identifier":  "{6B823A4C-719E-4833-975A-1BEFDCBDF389}"
    }
]
##[error]Run-Test-Exception: Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder  and retry. You might also have URL or Company name wrong.
*** Get XUnit Test file from [c:\Run\DevOps\TestResults.xml] to [C:\azp\agent\_work\1\s\XXX\TestResults.xml]
##[error]Cannot find path 'c:\Run\DevOps\TestResults.xml' because it does not exist.

*** Disconnect Docker session.
*** Docker session removed.
##[error]Cannot find path 'C:\azp\agent\_work\1\s\XXX\TestResults.xml' because it does not exist.
Finishing: ALOps Run TestSuite
```

I think the problem is the Dialog with the license expiration warning (causing the "CommunicationError"-parts).

**Expected behavior**
Well, I think it would be good to handle this warning and maybe ignore it somehow? 

**Screenshots**
No screenshots that make sense, I guess.

**Additional context**
If I missed anything important, please get in touch

**Comment by waldo1001** [comment]
We'll investigate.  

Can you confirm that it just works with a new license?
I won't put it as highest prio, as there is (or seems to be) an easy fix (new license).  But we'll look into it.

**Comment by waldo1001** [comment]
question - Is this still a problem? Seems that this issue has been resolved? 🤔

**Comment by waldo1001** [comment]
Well, 
Microsoft does use the "output channels" the wrong way (I was told - don't ask ;-)), so capturing warnings is a tedious thing to do .. .  So I'd be happy it's solved now.
Let's close it, and if it happens again, let's investigate it again ;-)
