### ISSUE TITLE
Error when testing in BC Insider

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#63]
Hello, 
when i use Image bcinsider.azurecr.io/bcsandbox-master:at i get the following result, the same Pipeline runs fine for BC15.00

*** AL-TestTool installation finished.
*** Set TCP Keep-Alive
*** Start TestSuite
*** Running TestSuite with authentication [NavUserPassword] with User [admin]
*** Run warm-up with page [130455]
*** Warm-up Client Context
*** Create Client Context
*** Run Available Tests for suite [DEFAULT] with page [130455]
Connect TestClient with page [130455]
*** Set [CurrentSuiteName] => [DEFAULT]
CommunicationError : Error reading JObject from JsonReader. Path '', line 0, position 0.
CommunicationError InnerException : Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass15_0.<EndInvokeInteractions>b__0() in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 306
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action) in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 181
##[error]Run-Test-Exception: ClientSession in Error
*** Get XUnit Test file from [c:\Run\DevOps\TestResults.xml] to [C:\DevOps_Host\agentATGRZ\_work\11\s\TestResults.xml]

**Comment by PatrickGrabensteiner** [comment]
Any news on this Topic?

**Comment by AdminHodor** [comment]
Hello @PatrickGrabensteiner ,

Could you please provide more info on this, we did not succeed in replicating this issue. Parameters seem to be correct in the log, could you please provide us with the yaml pipeline for this. 

Kind regards

**Comment by AdminHodor** [comment]
Dear @PatrickGrabensteiner ,

Could you please validate again, this should be solved from release v1.428.1159

Kind regards,
