### ISSUE TITLE
HTTP Error 503. The service is unavailable

### ISSUE THREAD

**Issue by fralanza** [HodorNV/ALOps#650]
I have an isseue  in a Onprem business central 22 upgraded from version 21

In a Cronus environment, version 22, on the same server, everything goes smootly.

In the upgraded 22, AlOpsExternalDeployer PUBLISH the .app, but doesn't install it.
In the Extension Management I have the .app published, so I have to install it manually.

In the Event Viewer the error is related to Microsoft.Dynamics.Nav.Management.dll with these details:

Type: Azure.RequestFailedException
Status: 503
Message:
  Service request failed.
  Status: 503 (Service Unavailable)
  
  Content:
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
  <HTML><HEAD><TITLE>Service Unavailable</TITLE>
  <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
  <BODY><h2>Service Unavailable</h2>
  <hr><p>HTTP Error 503. The service is unavailable.</p>
  </BODY></HTML>
  
  
  Headers:
  Connection: close
  Date: Fri, 23 Jun 2023 14:22:55 GMT
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 326
  Content-Type: text/html; charset=us-ascii
  
StackTrace:
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target)
     at Microsoft.Dynamics.Nav.Management.WriteObjectServerCommand.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Management
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target)
     at Microsoft.Dynamics.Nav.Management.WriteObjectServerCommand.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()

Any help?

**Comment by acjdekorte** [comment]
I had the same/simular problem, which I have solved by setting ManagementApiServicesEnabled to true. See also #630

**Comment by waldo1001** [comment]
That would be my guess too.  Thanks, @acjdekorte .
Can you check,  @fralanza ?

**Comment by waldo1001** [comment]
@fralanza?

**Comment by waldo1001** [comment]
I'm going to suppose it's fixed.  If not, please re-open, and provide the necessary details.
