### ISSUE TITLE
 ALOps Extension API - The system cannot find the file specified

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#749]
**Describe the bug**
Our deploy pipelines in several projects broke down after no change. It happened on friday between 05:00 - 10:45 Has an update been done?

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- deployment: Customer_Prod_Deploy
  displayName: Customer_Prod_Deploy
  pool: 'General BC Extensions'             
  environment: CustomerProd
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self 
          clean: true 
        - template: ./DevOps/ShowProjectVariables.yml@Templates       # Used for debugging        

        - task: ALOpsExtensionAPI@1  # Gets information on which extensions are installed on a given tenant
          displayName: 'ALOps Extension API - Get currently installed extensions' #
          inputs:
            interaction: get
            api_endpoint: $(APIEndpoint) 
            authentication: basic
            azure_tenant_id: default
            username: $(BCUserName)
            password: $(BCPassword)
            showdeploymentstatus: false

        - template: ./DevOps/DownloadArtifactsToFolder.yml@Templates
          parameters:
            displayName: '[DownloadArtifactsToFolder] Customer '
            #buildType: 'specific'
            project: 'XX'
            pipeline: 'XX'
            allowPartiallySucceededBuilds: true                             #Default = false
            branchName: 'refs/heads/release'                                   #Default = 'refs/heads/master''           
            itemPattern: '**/*_*APP.app'
            fileFilter: '*App.app'
            downloadPath: '$(System.ArtifactsDirectory)' 
        
        - task: PowerShell@2
          displayName: 'Remove Test apps'
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Cleaning [$(System.ArtifactsDirectory)] => [*_TEST.app]"
              Get-ChildItem -Path "$(System.ArtifactsDirectory)" -Filter "*_TEST.app" -Recurse | Remove-Item -Force:$true -Confirm:$false -ErrorAction SilentlyContinue

        - template: ./DevOps/ShowFilesInArtifactFolder.yml@Templates 
        
        - task: ALOpsExtensionAPI@1
          displayName: 'ALOps Extension API'
          inputs:
            interaction: batch
            api_endpoint: $(APIEndpoint) 
            authentication: basic
            azure_tenant_id: default
            username: $(BCUserName)
            password: $(BCPassword)
            artifact_path: '$(System.ArtifactsDirectory)\*_APP.app'
            showdeploymentstatus: false
            maxtries: 20

```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
==============================================================================
Task         : ALOps Extension API
Description  : Get/Publish extensions with the Business Central API
Version      : 1.463.5245
Author       : Hodor
Help         : Get/Publish extensions with the Business Central API.
==============================================================================
....

*** Loading module: [C:\bcartifacts.cache\onprem\***4.0.***64***0.***8056\platform\ServiceTier\program files\Microsoft Dynamics NAV\***40\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** BC Management DLL: C:\bcartifacts.cache\onprem\***4.0.***64***0.***8056\platform\ServiceTier\program files\Microsoft Dynamics NAV\***40\Service\Management\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\bcartifacts.cache\onprem\***4.0.***64***0.***8056\platform\ServiceTier\program files\Microsoft Dynamics NAV\***40\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\bcartifacts.cache\onprem\***4.0.***64***0.***8056\platform\ServiceTier\program files\Microsoft Dynamics NAV\***40\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Load module [Microsoft.Dynamics.Nav.Apps.Management]
*** BC App Management DLL: not available
*** Batch Publish Extensions
  * Artifact Path  : c:\vsts-agent-win-x64-***.***3.***\_work\89***\a\*_APP.app
*** Resolved Path  : c:\vsts-agent-win-x64-***.***3.***\_work\89***\a\*_APP.app
*** Get Available Applications from [c:\vsts-agent-win-x64-***.***3.***\_work\89***\a\*_APP.app].
*** Get [*.app] files recursive from [c:\vsts-agent-win-x64-***.***3.***\_work\89***\a\*_APP.app]
*** Found [***4] files.
*** Extract App detail from [C:\vsts-agent-win-x64-***.***3.***\_work\89***\a\Navet AB_Action Event Manager_***.0.***0***349.***5369_master_APP.app]
##[debug]Leaving C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\c6859736-95fd-450c-a0***-35a0dab***8cd***.ps***.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Get-NAVAppInfo : The system cannot find the file specified
##[debug]At C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\ps_modules\alops\9aabd83c-498c-4c40-8f***9-5***067c0***a***d.ps***:***7 char:***6
##[debug]+         $App = Get-NAVAppInfo -Path $AppFile.FullName
##[debug]+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Get-NAVAppInfo], Win3***Exception
##[debug]    + FullyQualifiedErrorId : System.ComponentModel.Win3***Exception,Microsoft.Dynamics.Nav.Management.GetNAVAppInfo
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-AppOrder, C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\ps_modules\alops\9aabd83c-498c-4c40-8f***9-5***067c0***a***d.ps***: line ***7
##[debug]at Batch-PublishAppsAPI, C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\ps_modules\api\4e5***5d75-345b-49b***-8470-***bc93***d***3d6b.ps***: line ***
##[debug]at Run-ALOpsExtensionAPIStep, C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\ps_modules\api\f9ce***fa***-d6***0-4***bb-bb45-7***59d***dd3***8***.ps***: line ***46
##[debug]at <ScriptBlock>, C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\c6859736-95fd-450c-a0***-35a0dab***8cd***.ps***: line ***3
##[debug]at <ScriptBlock>, C:\vsts-agent-win-x64-***.***3.***\_work\_tasks\ALOpsExtensionAPI_***d5eaeea-4***66-4583-bacd-6***ed666ed439\***.463.5***45\b0bd0fbd-98de-4945-96d8-bad3d76c8d45.ps***: line ***
##[debug]at <ScriptBlock>, <No file>: line ***
##[debug]at <ScriptBlock>, <No file>: line ***
##[debug]at <ScriptBlock>, <No file>: line ***8
##[debug]at <ScriptBlock>, <No file>: line ***
##[debug]Exception:
##[debug]System.ComponentModel.Win3***Exception (0x80004005): The system cannot find the file specified
##[debug]   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
##[debug]   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
##[debug]   at Prod.Management.Bridge.Runtime.Cmdlet.RunPowerShellScriptInIsolatedProcess(String script, String serializedParameters, ValueTuple`3 variables) in s:\repo\src\Platform\Management\Prod.Management.Bridge.Runtime\Cmdlet\Cmdlet.cs:line ***89
##[debug]   at Prod.Management.Bridge.Runtime.Cmdlet.RunScript(String cmdletName, Dictionary`*** parametersForScript) in s:\repo\src\Platform\Management\Prod.Management.Bridge.Runtime\Cmdlet\Cmdlet.cs:line ***53
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]The system cannot find the file specified
##[debug]Processed: ##vso[task.logissue type=error]The system cannot find the file specified
##[debug]Processed: ##vso[task.complete result=Failed]
Finishing: ALOps Extension API

```

**Expected behavior**
I expected that it would find the file and publish it to target server

**Comment by waldo1001** [comment]
No update - but v24 happened.

First of all, did you read this? https://github.com/HodorNV/ALOps/issues/745

**Comment by waldo1001** [comment]
Depends on the step.  
ExtensionAPI always takes latest artifact as it doesn't know any version info.  

You mean edit it here?  https://github.com/HodorNV/ALOps/issues/745

**Comment by NAVFreak** [comment]
Yes, edit #745. It through me off that it stated only BC24. It wasn't until I scrolled further down that I saw it applied to other versions as well

**Comment by waldo1001** [comment]
Done!
